// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args)
	{
	    int N = Integer.parseInt(args[0]);
		double rand = 0;
		double biggerThan = 0;
		double smallerThan = 0;

		while (N > 0)
		{
			rand = Math.random();
			if (rand > 0.5)
			{
				biggerThan ++;
			}
			else if (rand <= 0.5)
			{
				smallerThan ++;
			}
			N --;
		}

		double ratio = biggerThan / smallerThan ;

		if (biggerThan == 0.0 || smallerThan == 0.0)
		{
			System.out.println("> 0.5: " + (int)biggerThan);
			System.out.println("<= 0.5: " + (int)smallerThan);
		}
		else
		{
			System.out.println("> 0.5: " + (int)biggerThan);
			System.out.println("<= 0.5: " + (int)smallerThan);
			System.out.println("Ratio: " + ratio);
		}
	
		

	}
}
